# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-18 03:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='收货人姓名')),
                ('detailAddr', models.TextField(verbose_name='详细收货地址')),
                ('phone', models.CharField(max_length=12)),
                ('zipCode', models.IntegerField(null=True, verbose_name='邮编')),
            ],
            options={
                'db_table': 'sx_address',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='用户名')),
                ('email', models.CharField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=12, unique=True)),
                ('passwd', models.CharField(max_length=100)),
                ('photo', models.FileField(upload_to='upload')),
                ('state', models.BooleanField(default=True, verbose_name='用户状态')),
                ('money', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
            ],
            options={
                'db_table': 'sx_users',
            },
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.User'),
        ),
    ]
