# Generated by Django 2.0.7 on 2018-07-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='isselect',
            field=models.BooleanField(default=True, verbose_name='默认地址'),
        ),
    ]
