# Generated by Django 2.0.7 on 2018-07-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_address_isselect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='isselect',
            field=models.BooleanField(default=False, verbose_name='默认地址'),
        ),
    ]
