# Generated by Django 2.0.7 on 2018-07-21 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_address_isselect'),
        ('userapp', '0004_auto_20180720_2158'),
    ]

    operations = [
    ]
