# Generated by Django 2.0.7 on 2018-07-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_merge_20180721_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='isselect',
            field=models.BooleanField(default=False, verbose_name='默认地址'),
        ),
    ]
