# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-18 08:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='type',
            new_name='typeid',
        ),
        migrations.RemoveField(
            model_name='prodtyp',
            name='typesort',
        ),
    ]
