# Generated by Django 2.0.7 on 2018-07-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0002_auto_20180718_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='typeid',
            field=models.CharField(default='', max_length=20),
        ),
    ]
