# Generated by Django 2.0.7 on 2018-07-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0003_auto_20180718_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodtyp',
            name='typesort',
            field=models.IntegerField(default=1),
        ),
    ]
