# Generated by Django 2.0.7 on 2018-07-18 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0001_initial'),
        ('productapp', '0002_auto_20180718_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnt', models.IntegerField(default=1)),
                ('isSelected', models.BooleanField(default=True)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productapp.Products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.User')),
            ],
            options={
                'db_table': 'sx_cart',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderNum', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='订单号')),
                ('orderPrice', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payState', models.IntegerField(choices=[(0, '待支付'), (1, '已支付'), (2, '已退款')], default=0)),
                ('payType', models.IntegerField(choices=[(0, '余额'), (1, '支付宝'), (2, '微信')], default=0)),
                ('orderState', models.IntegerField(choices=[(0, '待支付'), (1, '待收货'), (2, '待评价'), (3, '已评价'), (4, '已取消')], default=0)),
                ('orderTime', models.DateTimeField(auto_now_add=True)),
                ('orderChangeTime', models.DateTimeField(auto_now=True)),
                ('order_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userapp.Address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.User')),
            ],
            options={
                'db_table': 'sx_order',
            },
        ),
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnt', models.IntegerField(default=1)),
                ('sumprice', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='某种商品的总价')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderapp.Order')),
                ('products', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='productapp.Products')),
            ],
            options={
                'db_table': 'sx_ordergoods',
            },
        ),
    ]
